function categories = otisCategories
% Default 11 otis categories.
%
% Syntax #####################
%
% categories = Resources.otisCategories;
% -> { 'balloon', ..., 'taj_mahal' }


% The categories
categories = ...
	{ 'balloon' ...
	, 'baseball' ...
	, 'bear' ...
	, 'cheetah' ...
	, 'ferrari' ...
	, 'gymnast' ...
	, 'helicopter' ...
	, 'kite' ...
	, 'pyramid' ...
	, 'statue_of_liberty' ...
	, 'taj_mahal' ...
	};


end
